services:
  tresorerieDB:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TRESORERIE}
      POSTGRES_USER: ${POSTGRES_USER_TRESORERIE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TRESORERIE}
    volumes:
      - pgdata_tresorerie:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_TRESORERIE} -d ${POSTGRES_DB_TRESORERIE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
            
  ef-migrator-tresorerieservice:
    image: komanatse/tresorerieservicesql:${DOCKER_TAG}
    environment:
      DB_HOST: tresorerieDB
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER_TRESORERIE}
      DB_PASSWORD: ${POSTGRES_PASSWORD_TRESORERIE}
      DB_NAME: ${POSTGRES_DB_TRESORERIE}
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
 
  tresorerieservice-api:
    image: komanatse/tresorerieservice:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT_TRESORERIE}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__Database=${CONNECTION_STRING_API}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
    ports:
      - target: 8080
        published: 9301
        protocol: tcp
        mode: host
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
      
networks:
  vault-net:
    external: true 
      
volumes:
  pgdata_tresorerie:
