services:
  dashadminDB:
    container_name: dashadminDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - pgdata_dashadmin:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net

  frontendadmin.web:
    container_name: frontendadmin.web
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "9011:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      backendadmin.api:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      resources:
        limits:
          memory: 1g

  backendadmin.api:
    container_name: backendadmin.api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Vault__EmailAdmin=${VAULT_EMAIL_ADMIN}
      - Vault__PasswordAdmin=${VAULT_PASSWORD_ADMIN}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__DashAdminDatabase=${CONNECTION_STRING_API}
    ports:
      - "9111:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - vault-net
    deploy:
      resources:
        limits:
          memory: 1g
    depends_on:
      dashadminDB:
        condition: service_healthy
               
networks:
  vault-net:
    external: true 
