services:
  dashadminDB:
    image: postgres:15
    container_name: dashadminDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - pgdata_dashadmin:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env
    networks:
      - vault-net
    
  ef-migrator-dashadmin:
    image: komanatse/frontendadminsql:${DOCKER_TAG}
    container_name: ef-migrator-dashadmin
    depends_on:
      dashadminDB:
        condition: service_healthy
    environment:
      DB_HOST: dashadminDB
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - vault-net
        
  frontendadmin.web:
    container_name: frontendadmin.web
    image: komanatse/frontendadmin:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ApiSettings__Uri=${API_SETTINGS_URL}
    volumes:
      - ./frontend/depensio.Web.Client/wwwroot/appsettings.json:/app/wwwroot/appsettings.json:ro
      - ./frontend/depensio.Web/appsettings.json:/app/appsettings.json:ro
    ports:
      - "9011:8080"
    depends_on:
      backendadmin.api:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - vault-net
      
  backendadmin.api:
    container_name: backendadmin.api
    image: komanatse/backendadmin:${DOCKER_TAG}
    restart: unless-stopped
    depends_on:
      ef-migrator:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Poduction
      - ASPNETCORE_HTTP_PORTS=8080     
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Vault__EmailAdmin=${VAULT_EMAIL_ADMIN}
      - Vault__PasswordAdmin=${VAULT_PASSWORD_ADMIN}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__DashAdminDatabase=${CONNECTION_STRING_API}
      - Service__MenuUrl=${MENU_SERVICE_URL}
    ports:
      - "9111:8080"
    env_file:
      - ./.env
    networks:
      - vault-net
            
networks:
  vault-net:
    external: true 
      
volumes:
  pgdata_dashadmin: