services:
  tresorerieDB:
    image: postgres:17
    container_name: tresorerieDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TRESORERIE}
      POSTGRES_USER: ${POSTGRES_USER_TRESORERIE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TRESORERIE}
    ports:
      - "127.0.0.1:5443:5432"
    volumes:
      - pgdata_tresorerie:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD_TRESORERIE psql -U $$POSTGRES_USER_TRESORERIE -d $$POSTGRES_DB_TRESORERIE -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net
            
  ef-migrator_tresorerieservice:
    image: komanatse/tresorerieservicesql:${DOCKER_TAG}
    container_name: ef-migrator_tresorerieservice
    depends_on:
      tresorerieDB:
        condition: service_healthy
    environment:
      DB_HOST: tresorerieDB
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER_TRESORERIE}
      DB_PASSWORD: ${POSTGRES_PASSWORD_TRESORERIE}
      DB_NAME: ${POSTGRES_DB_TRESORERIE}
    env_file:
      - ./.env
    networks:
      - vault-net
 
  tresorerieservice.api:
    container_name: tresorerieservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT_TRESORERIE}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__Database=${CONNECTION_STRING_API}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
    ports:
      - "9301:8080"
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net
      
networks:
  vault-net:
    external: true 
      
volumes:
  pgdata_tresorerie: