services:
  dashadminDB:
    container_name: dashadminDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - pgdata_dashadmin:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net

  frontendadmin.web:
    container_name: frontendadmin.web
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081  
      - ApiSettings__Uri=${API_SETTINGS_URL}
    ports:
      - "9011:8080"
      - "9012:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      backendadmin.api:
        condition: service_started
      menuservice.api:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      resources:
        limits:
          memory: 1g

  backendadmin.api:
    container_name: backendadmin.api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081  
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Vault__EmailAdmin=${VAULT_EMAIL_ADMIN}
      - Vault__PasswordAdmin=${VAULT_PASSWORD_ADMIN}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__DashAdminDatabase=${CONNECTION_STRING_API}
      - Service__MenuUrl=${MENU_SERVICE_URL}
    ports:
      - "9111:8080"
      - "9112:8081"
    env_file:
      - ./.env
    networks:
      - vault-net
    deploy:
      resources:
        limits:
          memory: 1g
    depends_on:
      dashadminDB:
        condition: service_healthy
               
        
  menuDB:
    container_name: menuDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_MENU}
      POSTGRES_USER: ${POSTGRES_USER_MENU}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MENU}
    ports:
      - "5438:5432"
    volumes:
      - pgdata_menu:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD_MENU psql -U $$POSTGRES_USER_MENU -d $$POSTGRES_DB_MENU -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net
 
  menuservice.api:
    container_name: menuservice.api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT_MENU}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__MenuDatabase=${CONNECTION_STRING_API}
    ports:
      - "9021:8080"
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - vault-net
 
  magasinDB:
    container_name: magasinDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_MAGASIN}
      POSTGRES_USER: ${POSTGRES_USER_MAGASIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MAGASIN}
    ports:
      - "5442:5432"
    volumes:
      - pgdata_magasin:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD_MAGASIN psql -U $$POSTGRES_USER_MAGASIN -d $$POSTGRES_DB_MAGASIN -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net
 
  magasinservice.api:
    container_name: magasinservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT_MAGASIN}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__Database=${CONNECTION_STRING_API}
    ports:
      - "9211:8080"
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net
 
  tresorerieservice.api:
    container_name: tresorerieservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Vault__Uri=${VAULT_URI}
      - Vault__RoleId=${VAULT_ROLE_ID}
      - Vault__SecretId=${VAULT_SECRET_ID}
      - Vault__PathMountPoint=${VAULT_PATH_MOUNT_POINT_TRESORERIE}
      - Vault__MountPoint=${VAULT_MOUNT_POINT}
      - Allow__Origins=${CORS_ALLOWED_ORIGINS}
      - ConnectionStrings__Database=${CONNECTION_STRING_API}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
    ports:
      - "9301:8080"
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net

       
  tresorerieDB:
    container_name: tresorerieDB
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TRESORERIE}
      POSTGRES_USER: ${POSTGRES_USER_TRESORERIE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TRESORERIE}
    ports:
      - "5443:5432"
    volumes:
      - pgdata_tresorerie:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD_TRESORERIE psql -U $$POSTGRES_USER_TRESORERIE -d $$POSTGRES_DB_TRESORERIE -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - ./.env
    networks:
      - vault-net


networks:
  vault-net:
    external: true 





