name: BACKENDADMIN - Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'BackendAdmin/**'
      - 'FrontendAdmin/**'
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'BackendAdmin/**'
      - 'FrontendAdmin/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    permissions:
      contents: read
      packages: write
    with:
      image_api: backendadmin
      image_sql: frontendadminsql
      image_web: frontendadmin
      dockerfile_api: BackendAdmin/BackendAdmin.Api/Dockerfile
      dockerfile_sql: backendadminsql.Dockerfile
      dockerfile_web: FrontendAdmin/FrontendAdmin.Web/Dockerfile
      ef_project: BackendAdmin/BackendAdmin.Infrastructure
      ef_startup_project: BackendAdmin/BackendAdmin.Api
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
