name: MENUSERVICE - Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths:
      - 'Services/MenuService/**'
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'Services/MenuService/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    permissions:
      contents: read
      packages: write
    with:
      image_api: menuservice
      image_sql: menuservicesql
      dockerfile_api: Services/MenuService/MenuService.Api/Dockerfile
      dockerfile_sql: backendadminsql.Dockerfile
      ef_project: Services/MenuService/MenuService.Infrastructure
      ef_startup_project: Services/MenuService/MenuService.Api
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
