name: TRESORERIESERVICE - Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image_api: tresorerieservice
      image_sql: tresorerieservicesql
      dockerfile_api: Services/TresorerieService/TresorerieService.Api/Dockerfile
      dockerfile_sql: backendadminsql.Dockerfile
      ef_project: Services/TresorerieService/TresorerieService.Infrastructure
      ef_startup_project: Services/TresorerieService/TresorerieService.Api
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
